client_config_backend: file
client_config:
    client_id: 84420110064-qo2j067loorjmotsv46mv9knc5kg6101.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive